README.md
=> docs(Readme): add setup instructions

package.json, src/selectorNameBase.ts, test/componentSelectorTypeRule.spec.ts
=> Es6 template string literals support

src/util/selectorValidator.ts, test/componentSelectorNameRule.spec.ts
=> fix(util): kebab-case doesn't allow non-hyphen selector

src/importDestructuringSpacingRule.ts, test/importDestructuringSpacingRule.spec.ts
Thanks to @dweitz43 for creating the original rule.
=> feat(rules): add import destructuring spacing rule

src/noAccessMissingMemberRule.ts, test/noAccessMissingMemberRule.spec.ts
=> fix(noAccessMissingMember): search among all declared members

src/angular/ng2Walker.ts, src/angular/recursiveAngularExpressionVisitor.ts, test/noAccessMissingMemberRule.spec.ts
=> fix(noAccessMissingMember): set the expression in bounded property

.travis.yml, package.json, src/angular/ng2Walker.ts, src/angular/recursiveAngularExpressionVisitor.ts, src/componentClassSuffixRule.ts, src/pipeImpureRule.ts, src/pipeNamingRule.ts, test/directiveClassSuffix.spec.ts, test/pipeImpureRule.spec.ts, test/pipeNamingRule.spec.ts
=> refactor: remove dirty hack for proper calculation of interpolation offset

src/pipeNamingRule.ts, src/selectorNameBase.ts, src/util/selectorValidator.ts, test/componentSelectorRule.spec.ts, test/directiveSelectorRule.spec.ts, test/pipeNamingRule.spec.ts
=> fix(selectors): use proper check for selector prefix

package.json
tslint 4.1 was released yesterday https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v410
=> chore(dependencies) upgrade tslint to 4.1

src/angular/config.ts, src/angular/templates/basicTemplateAstVisitor.ts, src/angular/templates/templateParser.ts, test/noAccessMissingMemberRule.spec.ts
=> fix: add support for *ngIf

src/templatesUsePublicRule.ts, test/noAccessMissingMemberRule.spec.ts, test/templatesUsePublicRule.spec.ts
=> fix: proper check for public members

test/invokeInjectableRule.spec.ts, test/testHelper.ts
=> feat(test): add easier way to annotate code

package.json, src/angular/ng2Walker.ts, src/noUnusedCssRule.ts
=> fix(rules): log parse errors and fix noUnusedCss

package.json, src/angular/templates/basicTemplateAstVisitor.ts, src/angular/templates/recursiveAngularExpressionVisitor.ts, src/angular/templates/templateParser.ts, src/noAccessMissingMemberRule.ts, src/templatesUsePublicRule.ts, test/componentClassSuffixRule.spec.ts, test/componentSelectorRule.spec.ts, test/directiveClassSuffix.spec.ts, test/directiveSelectorRule.spec.ts, test/importDestructuringSpacingRule.spec.ts, test/invokeInjectableRule.spec.ts, test/noAccessMissingMemberRule.spec.ts, test/noAttributeParameterDecoratorRule.spec.ts, test/noForwardRefRule.spec.ts, test/noInputRenameRule.spec.ts, test/noOutputRenameRule.spec.ts, test/noUnusedCssRule.spec.ts, test/pipeImpureRule.spec.ts, test/pipeNamingRule.spec.ts, test/templatesUsePublicRule.spec.ts, test/testHelper.ts, test/useHostPropertyDecoratorRule.spec.ts, test/useInputPropertyDecoratorRule.spec.ts, test/useLifeCycleInterfaceRule.spec.ts, test/useOutputPropertyDecoratorRule.spec.ts, test/usePipeTransformInterfaceRule.spec.ts, yarn.lock
Includes:
Refactored error tests to use assertAnnotated,
Support for multi-line errors,
Support for Angular 4.00-rc2
=> Tests refactor

.editorconfig, test/testHelper.ts
So it took me a while to understand how tests work (and tests are the best place to start looking at when digging at source code for the first time), so I figured I'd help others understand what functions are used for.
If I misunderstood something please comment so I can edit the explanation.
(Or, if we disagree about having these kinds of "docs", maybe we could open a wiki "guide/tutorial" about understanding the code and going towards a first PR?)
---
Also added an `.editorconfig` file with just two basic rules for now (I'll go though other files in a different PR tonight).
=> docs(testHelper): explain test helper functions

src/selectorNameBase.ts, test/componentSelectorRule.spec.ts
=> fix(rules): order problem with multiple prefixes for selector

src/templateToNgTemplateRule.ts
=> fix(Rule): templateToNgTemplateRule metadata property

src/angular/ngWalker.ts, src/angular/ngWalkerFactoryUtils.ts, src/angular/sourceMappingVisitor.ts, src/angular/styles/cssParser.ts, src/angular/templates/basicTemplateAstVisitor.ts, src/angular/templates/templateParser.ts, src/angularWhitespaceRule.ts, src/index.ts, src/pipeImpureRule.ts, src/propertyDecoratorBase.ts, src/templateToNgTemplateRule.ts, src/useViewEncapsulationRule.ts, test/angular/metadataReader.spec.ts, test/angular/sourceMappingVisitor.spec.ts, test/angularWhitespaceRule.spec.ts
First part of https://github.com/mgechev/codelyzer/issues/314
=> feat: whitespace in interpolation

src/angular/ngWalker.ts
Fix #336 
@wKoza this should solve the problem.
=> fix: report template warnings only once

src/angularWhitespaceRule.ts, test/angularWhitespaceRule.spec.ts
=> fix: handle case when whitespace on one side of interpolation

src/useViewEncapsulationRule.ts, test/useViewEncapsulationRule.spec.ts
=> ViewEncapsulation concerns only components

src/angularWhitespaceRule.ts, src/bananaInBoxRule.ts, src/noUnusedCssRule.ts, src/templateToNgTemplateRule.ts, src/templatesUsePublicRule.ts, src/useLifeCycleInterfaceRule.ts
=> refactor(rules): cleanup rules

docs/_data/rules.json, docs/dist/src/noUnusedCssRule.js, docs/rules/no-unused-css-rule/index.html, src/noUnusedCssRule.ts
=> rename rule noUnusedCss

test/angularWhitespaceRule.spec.ts
Adds a failing test to reproduce #346
=> test: add failing test for check-pipe in ngFor

src/angular/metadataReader.ts, src/angular/ngWalker.ts, src/decoratorNotAllowedRule.ts, src/index.ts, test/decoratorNotAllowedRule.spec.ts
=> Decorator not allowed

src/bananaInBoxRule.ts, test/bananaInBoxRule.spec.ts
=> fix(rules) : fix banana-in-a-box rule

src/angular/config.ts
See https://github.com/mgechev/codelyzer/issues/394
=> fix: support ngForm for directives

test/angularWhitespaceRule.spec.ts
=> fix(test) : add unit test for check-pipe rule

src/contextualLifeCycleRule.ts, test/contextualLifeCycleRule.spec.ts
=> fix(rule) : directive supports 'View' lifecycle hooks

package.json, src/angular/templates/basicTemplateAstVisitor.ts, src/angularWhitespaceRule.ts, test/angularWhitespaceRule.spec.ts
Issue #412 - part I
The second part of this issue concerns HTML entities. It's less trivial.
=> fix(rule) : parentheses supported in expression

docs/src/worker.ts
rename no-output-on-prefix-name to no-output-on-prefix in doc/src/worker.ts
=> rename no-output-on-prefix-name to no-output-on-prefix

src/angular/ngWalker.ts, src/decoratorNotAllowedRule.ts, test/angular/ngWalker.spec.ts, test/decoratorNotAllowedRule.spec.ts
=> fix(rule) : allow many declarations in a file

src/angularWhitespaceRule.ts, src/bananaInBoxRule.ts, src/noUnusedCssRule.ts, src/templatesNoNegatedAsyncRule.ts
Improve the documentation by adding hasFix boolean
=> fix(doc) : add hasFix boolean

README.md
=> fix(doc): fix rules & dependencies

src/angularWhitespaceRule.ts, test/angularWhitespaceRule.spec.ts
=> fix two bugs of angular-whitespace, update the spec code

src/i18nRule.ts, test/i18nRule.spec.ts
=> fix(i18n): do not warn with interpolation in i18n element

README.md
@mgechev here you go :)
relates to #491
=> docs(README): add disable a rule that validates template or styles

README.md, docs/_data/rules.json, docs/rules/angular-whitespace/index.html, docs/rules/banana-in-box/index.html, docs/rules/no-output-named-after-standard-event/index.html, docs/rules/no-unused-css/index.html, docs/rules/templates-no-negated-async/index.html, docs/rules/trackBy-function/index.html
=>  docs: add missing documentation

README.md
drop deprecated rule in our configuration
drop deleted rule in our examples
Add some rules in our examples
=> fix consistence readme

src/angular/config.ts, src/index.ts, src/templateCyclomaticComplexityRule.ts, test/templateCyclomaticComplexityRule.spec.ts
=> feat(rule): cyclomatic complexity rule

src/templateConditionalComplexityRule.ts, src/templateCyclomaticComplexityRule.ts, test/templateConditionalComplexityRule.spec.ts, test/templateCyclomaticComplexityRule.spec.ts
=> fix(rules): Fix message when a failure occurs

test/i18nRule.spec.ts
The commit 7d0eaf6  corrected part of this issue #497
=> fix(rules): Add i18n test related to  #497

src/contextualLifeCycleRule.ts, test/contextualLifeCycleRule.spec.ts
=> Fix contextual-life-cycle when we have more than one class in a file

package-lock.json, package.json, src/angular/templates/jitReflector.ts, yarn.lock
prepares the transition to Angular 6 ...
Supersedes #531 
Fix #525
=> Bump Angular 6

src/index.ts, src/preferOutputReadonlyRule.ts, test/preferOutputReadonlyRule.spec.ts
=> feat(rule): add prefer-output-readonly rule

src/index.ts, src/noConflictingLifeCycleHooksRule.ts, test/noConflictingLifeCycleHooksRule.spec.ts
=> feat(rule): add no-conflicting-life-cycle-hooks rule

src/contextualLifeCycleRule.ts, src/noConflictingLifeCycleHooksRule.ts, src/noInputRenameRule.ts, src/noLifeCycleCallRule.ts, src/useLifeCycleInterfaceRule.ts, test/noLifeCycleCallRule.spec.ts, test/useLifeCycleInterfaceRule.spec.ts
~~Basically changes `life cycle` to `lifecycle`, other changes are prettier changes.~~~
Edit: Basically changes `lifecycle` to `life cycle`, other changes are prettier changes.
=> refactor: change lifecycle to life cycle

src/index.ts
=> fix(release): add 'no-template-call-expression' rule to index

src/contextualLifeCycleRule.ts, src/decoratorNotAllowedRule.ts, src/enforceComponentSelectorRule.ts, src/maxInlineDeclarationsRule.ts, src/noAttributeParameterDecoratorRule.ts, src/noOutputNamedAfterStandardEventRule.ts, src/noOutputOnPrefixRule.ts, src/noTemplateCallExpressionRule.ts, src/pipeImpureRule.ts, src/pipeNamingRule.ts, src/preferOutputReadonlyRule.ts, src/templateConditionalComplexityRule.ts, src/templateCyclomaticComplexityRule.ts, src/templatesNoNegatedAsyncRule.ts, src/trackByFunctionRule.ts, src/usePipeDecoratorRule.ts, src/useViewEncapsulationRule.ts, test/enforceComponentSelectorRule.spec.ts, test/noOutputNamedAfterStandardEventRule.spec.ts, test/noTemplateCallExpressionRule.spec.ts, test/pipeImpureRule.spec.ts, test/pipeNamingRule.spec.ts
This normalize (and fix, in some cases) all rule's description, failure and rationale.
=> docs: fix inconsistent descriptions

README.md
=> Change status of no-conflicting-life-cycle-hooks to experimental 

CODE_OF_CONDUCT.md
Used the default template. Let me know if you have any suggestions for improvement.
=> docs: introduce code of conduct

docs/dist/src/useLifeCycleInterfaceRule.js
=> Fix typo of length closes #681

package-lock.json, package.json, yarn.lock
=> feat: support Angular 7.0

src/templateNoNegatedAsyncRule.ts
See https://github.com/mgechev/codelyzer/issues/615#issuecomment-464817849.
=> refactor(rule): change failure message for 'template-no-negated-async'

src/angular/config.ts
=> feat: add support for svg templates

src/index.ts
=> fix(rule): add template-accessibility-elements-content to index.ts
