mgechev/codelyzer

- package.json
You will now need to install typings by hand with: `npm run typings -- install` but now you won't force endusers to have typings installed.
> chore: make typings a normal script

- src/pipeImpureRule.ts
- test/pipeImpureRule.spec.ts
Added a simple rule for checking impure pipes (the rule was derived from source of the pipe-naming rule).
> feat(rules): add impure pipe rule

- package.json
- typings.json
Changes:
mocha 2.4.5 => 3.0.2
ts-node 0.5.5 => 1.2.2
tslint 3.9.0 => 3.14.0 (dev) ^3.9.0 (peer)
typings 0.8.1 => 1.3.2
Builds and runs tests successfully. The `peerDependencies` change is helpful for those who want to use a newer version of tslint with codelyzer.
> Upgrade dependencies and relax peer dependency requirement

- package.json
- src/angular/config.ts
- src/angular/recursiveAngularExpressionVisitor.ts
- src/angular/templateParser.ts
1. Migrate to the newest private API.
2. Externalize the interpolation config.
> fix(parseTemplate): migrate to the new private API

- src/noAccessMissingMemberRule.ts
- src/templatesUsePublicRule.ts
- test/noAccessMissingMemberRule.spec.ts
- test/templatesUsePublicRule.spec.ts
> fix(rules): handle index access in missing property access in templates

- src/angular/config.ts
In Atom Editor when using linter-tslint and codelyzer 2.0.0-beta.1 we're unable to lint files currently because app-root-path fails. I'm not sure why? But putting it inside the try catch to fail silently stops it from being broken.
> Atom fatal error from app-root-path

- src/noAttributeParameterDecoratorRule.ts
- src/walkerFactory/walkerFactory.ts
- src/walkerFactory/walkerFn.ts
Fixes errors from building with declaration file (#221)
Tested with `npm run tsc -- -p tsconfig-release.json`.
Making `walkerBuilder` private as it should be local to the Rule class.
> Updating visibility and export to fix d.ts build error

- src/templatesUsePublicRule.ts
- test/templatesUsePublicRule.spec.ts
Pass the class member name to the error for more clarification
fixes #229
> fix(templatesUsePublicRule): Pass member name back through error

- src/angular/sourceMappingVisitor.ts
- src/noUnusedCssRule.ts
- src/useLifeCycleInterfaceRule.ts
- test/angular/sourceMappingVisitor.spec.ts
- test/noUnusedCssRule.spec.ts
- test/testHelper.ts
Fix https://github.com/mgechev/codelyzer/issues/245
Fix https://github.com/mgechev/codelyzer/issues/244
> Unused css auto-fix & better source position mapping

- README.md
- index.js
- package.json
Like most of the other TSLint plugins it would be great to be able to run tslint with codelizer without the required node_modules directory. Ideally using codelizer from the path.
This PR exports the rules, allowing to use the `extends` field in tslint.json. This is also similar to the way ESLint plugins work.
As an example you can check https://github.com/buzinas/tslint-eslint-rules/blob/master/index.js
This PR still allows for the previous way without breaking compatibility.
> Allow tslint to run with codelizer without node_modules in the root

- src/componentClassSuffixRule.ts
- src/componentSelectorRule.ts
- src/directiveClassSuffixRule.ts
- src/directiveSelectorRule.ts
- src/importDestructuringSpacingRule.ts
- src/invokeInjectableRule.ts
- src/noAccessMissingMemberRule.ts
- src/noAttributeParameterDecoratorRule.ts
- src/noForwardRefRule.ts
- src/noInputRenameRule.ts
- src/noOutputRenameRule.ts
- src/noUnusedCssRule.ts
- src/pipeImpureRule.ts
- src/pipeNamingRule.ts
- src/templatesUsePublicRule.ts
- src/useHostPropertyDecoratorRule.ts
- src/useInputPropertyDecoratorRule.ts
- src/useLifeCycleInterfaceRule.ts
- src/useOutputPropertyDecoratorRule.ts
- src/usePipeTransformInterfaceRule.ts
I realized too late that some of the rules are not in v3 anymore, but oh well. I tried quoting the official styleguide whenever it made sense in the context.
I've seen `Lint.Utils.dedent` in tslint source code so no idea how exactly it works, but we'll see after building the docs page and change it accordingly later, I guess.
> docs(meta): add metadata to all rules

- test/componentSelectorRule.spec.ts
- test/testHelper.ts
The [way `tslint` does it](https://github.com/palantir/tslint/blob/master/test/rules/jsdoc-format/jsdoc.js.lint) seems like an overkill and is actually less readable for our small tests (too much clutter). It looks much clearer to me like this. We can add the `[failure]` syntax when we feel the need for it. There are enough symbols like this; it basically it just has to be a symbol which is not otherwise used in the snippet.
I updated a (kinda) random test to test the new helper function, although it doesn't make _that_ much sense to test two same error messages (I couldn't find an existing rule on master branch in which two different error messages can happen in the same context).
> test(*): support multiple annotated failures

- package.json
- src/angular/styles/chars.ts
- src/angular/styles/parseUtil.ts
- src/angular/templates/basicTemplateAstVisitor.ts
- src/angular/templates/recursiveAngularExpressionVisitor.ts
- src/angular/templates/referenceCollectorVisitor.ts
- src/angular/templates/templateParser.ts
- src/componentClassSuffixRule.ts
- src/componentSelectorRule.ts
- src/directiveSelectorRule.ts
- src/importDestructuringSpacingRule.ts
- src/noAccessMissingMemberRule.ts
- src/noAttributeParameterDecoratorRule.ts
- src/noUnusedCssRule.ts
- src/pipeImpureRule.ts
- src/pipeNamingRule.ts
- src/templatesUsePublicRule.ts
- src/useLifeCycleInterfaceRule.ts
- src/usePipeDecoratorRule.ts
- test/testHelper.ts
- test/usePipeDecoratorRule.spec.ts
> add usePipeDecoratorRule, refactored linting erros, updated to rc5

- src/templatesNoNegatedAsyncRule.ts
- test/templatesNoNegatedAsyncRule.spec.ts
Angular's async pipes emit `null` initially, prior to the observable emitting
any values, or the promise resolving. This can cause negations, like
`*ngIf="!(myConditional | async)"` to thrash the layout and cause expensive
side-effects like firing off XHR requests for a component which should not
be shown.
This PR adds a linting rule which fails on usages of !(expr | async) and
(expr | async) == false.
> feat: add a no-negated-async rule

- src/bananaInBoxRule.ts
- src/index.ts
- test/bananaInBoxRule.spec.ts
> feat: add "banana in a box" rule

- src/componentClassSuffixRule.ts
- src/componentSelectorRule.ts
- src/directiveClassSuffixRule.ts
- src/directiveSelectorRule.ts
- src/noInputRenameRule.ts
- src/noOutputRenameRule.ts
- src/useHostPropertyDecoratorRule.ts
- src/useInputPropertyDecoratorRule.ts
- src/useLifeCycleInterfaceRule.ts
- src/useOutputPropertyDecoratorRule.ts
> Fix links to angular.io styleguide

- src/importDestructuringSpacingRule.ts
fix #358 by renaming import-destructing-spacing to import-destructuring-spacing
> renaming import-destructing-spacing to import-destructuring-spacing

- src/angular/ngWalker.ts
- src/angularWhitespaceRule.ts
- test/angularWhitespaceRule.spec.ts
> Ensure whitespaces after semicolon in structural dir

- src/directiveClassSuffixRule.ts
- test/directiveClassSuffix.spec.ts
- Allow `Validator` suffix if any of the implemented interfaces by a
directive ends with `Validator`.
- Allow multiple suffixes for a directive.
Fix #397
> fix: support validation directives and extra suffixes

- src/angular/templates/templateParser.ts
closes #416  
I think that we should push a new release with this fix.
> fix(parser) : support for Angular 4.4.1

- package-lock.json
- src/noAttributeParameterDecoratorRule.ts
- src/util/utils.ts
- test/noAttributeParameterDecoratorRule.spec.ts
> fix(rules): handle anonymous class

- src/angular/config.ts
- test/noAccessMissingMemberRule.spec.ts
Related to #437
I noticed that there seem to be a lot of directives that has exports that are not configured (e.g. `mat-button` with `matButton` export). But I deemed it out of scope here, I just added the equivalent `mat` selectors and exports for the existing directives.
I also had trouble running tests on windows (there is no `cp` command), so I'll just hope it passes on the CI.
> fix: directive config for material2 beta.12

- src/index.ts
Add the i18n rule to index.ts so that it is included in the npm package.
Fix #433
> fix: add i18n rule to npm package

- src/angular/config.ts
- test/noAccessMissingMemberRule.spec.ts
Fixes linting error *"The property "foo" that you're trying to access does not exist in the class declaration"* for the following template example:
```
<input type="text" [matAutocomplete]="foo">
<mat-autocomplete #foo="matAutocomplete">
<mat-option *ngFor="let v of values" [value]="v">{{ v }}</mat-option>
</mat-autocomplete>
```
I only added the fix for the new `mat-` prefixed version, due to the other being deprecated. But if preferred I can add it with `md` prefix too.
> fix: added support for mat-autocomplete

- src/angularWhitespaceRule.ts
- test/angularWhitespaceRule.spec.ts
**check multiple semicolons inside the directive expressions for angular-whitespace rule**
The `check-semicolon` rule of `angular-whitespace` could only check out and fix the first error when there are mutiple semicolon errors inside the directive expressions. For example:
```html
<h3 *ngIf="date | date:'fullDate';let dateString;else errorDate">{{ dateString }}</h3>
<ng-template #errorDate>error date!</ng-template>
```
Only the first error ( `;let` ) should be check out and fixed. If someone want to fix all of two errors of this example, it must run the `tslint --fix` command twice.
I have rewritten the codes of `check-semicolon` to solve the problem, also add 5 test cases, one for success check, and 4 for fail/apply proper replacements.
> check multiple semicolons inside the directive expressions

- src/noOutputOnPrefixRule.ts
- test/noOutputOnPrefixRule.spec.ts
> fix(no-output-on-prefix): do not warn on properly named props

- src/angular/styles/chars.ts
- src/angular/styles/cssAst.ts
- src/angular/styles/cssLexer.ts
- src/angular/styles/cssParser.ts
- src/angular/styles/parseUtil.ts
- test/noUnusedCssRule.spec.ts
> fix(core): update the CSS parser

- package-lock.json
- package.json
- src/trackByFunctionRule.ts
- test/trackByRule.spec.ts
- No longer split by "=" as this broke `*ngFor` statements with `let i = index` statements or similar.
- Add test to cover cases like this.
- Fix line length lint error (maybe only on windows).
> fix(trackBy): fix rule when ngFor statements include let assignments

- src/index.ts
- src/noInputPrefixRule.ts
- test/noInputPrefixRule.spec.ts
Not sure, if this might make sense for you guys. But since, I was gonna do it for one of our internal libraries, I though to do it here first. 
Maybe you like it, or maybe not :)
If you'd like it I can also extend it and has it to include other `boolean` prefixes to be excluded from inputs, such as `has`, `should` `can` etc.. And it can be renamed too `no-input-boolean-prefixes`, maybe?
The whole point for the rules is to disable boolean prefixes from input properties. I personally find them a bit dirty, even though they are not listing anyways if one should do them or not in the Angular style guide. But, considering even the native html attributes like `disabled`, `checked` these are never prefixed.
Let me know what are your thoughts anyways :) I'd appreciate any type of feedback Thanks.
> feat: add `no-input-prefix` rule

- src/index.ts
At the moment doing something like
```json
{
"extends": ["codelyzer"],
"rules": {
"angular-whitespace": [true, "check-interpolation", "check-semicolon"],
"banana-in-box": true,
"templates-no-negated-async": true,
"directive-selector": [true, "attribute", "sg", "camelCase"],
}
}
```
Will not work and you'll end up with loads of errors example
```bash
Could not find implementations for the following rules specified in the configuration:
angular-whitespace
banana-in-box
contextual-life-cycle
```
This is because tslint requires a `rulesDirectory` to resolve the rules.
> fix: cannot find rules

- README.md
This is quite helpful as in order to check what’s the latest version one doesn’t need to check the chane log or package.json
> docs(README): add npm version badge

- test/angularWhitespaceRule.spec.ts
The 'trackBy' micro-syntax must use a function to check references, instead of references to object properties directly.
The old testing cases I written were wrong usages/examples, that should be fixed.
> fix wrong usages of 'trackBy' micro-syntax in testing cases

- src/noOutputNamedAfterStandardEventRule.ts
- test/noOutputNamedAfterStandardEventRule.spec.ts
> fix(537): no-output-named-after-standard-event checks output rename

- src/i18nRule.ts
- test/i18nRule.spec.ts
This fix will address #530 regarding `ng-container` checking.  I verified that the unit test added for #506 still passes.
It will also address another problem that my team was having which was causing the `check-text` to report failure for nested items like this:
```
<ul i18n="@@myList">
<li>List Item 1</li>
<li>List Item 2</li>
<li>List Item 3</li>
</ul>
```
This is valid syntax resulting in the following xlf output:
```
<trans-unit id="myList" datatype="html">
<source>
<x id="START_LIST_ITEM" ctype="x-li" equiv-text="&lt;li&gt;"/>List Item 1<x id="CLOSE_LIST_ITEM" ctype="x-li" equiv-text="&lt;/li&gt;"/>
<x id="START_LIST_ITEM" ctype="x-li" equiv-text="&lt;li&gt;"/>List Item 2<x id="CLOSE_LIST_ITEM" ctype="x-li" equiv-text="&lt;/li&gt;"/>
<x id="START_LIST_ITEM" ctype="x-li" …
```
> Add support for nested i18n items and removed ng-container restriction

- src/maxInlineDeclarationsRule.ts
- test/fixtures/inlineTemplateMaxLines/large.css
- test/fixtures/inlineTemplateMaxLines/large.html
- test/inlineTemplateMaxLinesRule.spec.ts
* Rule now only validates inline template and styles, before this fix it was looking also into template / style files
> fix(rule): inline template max lines rule

- src/noInputRenameRule.ts
- test/noInputRenameRule.spec.ts
This:
- Change the failure message, because the rule isn't only for directives as the current message describes;
- Do not report a warning for a special case described in #224 and in [Styleguide](https://angular.io/guide/styleguide#avoid-aliasing-inputs-and-outputs):
> You should use an alias when the directive name is also an input property, and the directive name doesn't describe the property.
- Report a warning for the following example (described in #374):
```
@Component...
...
@Input('myInput') myInput: any;
```
Fixes #374.
> feat(rule): add special case to no-input-rename rule

- src/index.ts
- src/noQueriesParameterRule.ts
- test/noQueriesParameterRule.spec.ts
Basically the same as `useHostPropertyDecorator`.
> feat(rule): add no-queries-parameter rule

- package-lock.json
- package.json
- src/angular/metadataReader.ts
- src/angular/ngWalker.ts
- src/noTemplateCallExpressionRule.ts
- src/propertyDecoratorBase.ts
- src/selectorNameBase.ts
- src/usePipeDecoratorRule.ts
- src/util/astQuery.ts
- src/util/utils.ts
- test/angular/metadataReader.spec.ts
- test/angular/sourceMappingVisitor.spec.ts
- test/angular/urlResolvers/urlResolver.spec.ts
- yarn.lock
Migrate to TypeScript 2.8 and open the version range.
Fix https://github.com/mgechev/codelyzer/issues/583.
> chore: update to typescript 2.8

- src/noInputRenameRule.ts
- test/noInputRenameRule.spec.ts
In the hope that it clarifies things:
- A component shouldn't rename its @Input
- A directive shouldn't rename its @Input expect when the directive name is also an input property and the directive name doesn't describe the property.
Fixes #580
> fix noInputRenameRule

- src/preferInlineDecoratorRule.ts
- test/preferInlineDecoratorRule.spec.ts
This ensures that decorators are on the same line as the property it decorates.
Failure example:
```
@Input()
x: string;
```
Success example:
```
@Input() x: string;
```
Closes #549.
**Note that I've tried to implement a fix for this.** Let me know if I did something wrong.
> feat(rule): add prefer-inline-decorator rule

- src/pipeNamingRule.ts
Once someone try to use this _deprecated_ rule, it'll show a warning like:
> pipe-naming is deprecated. Message here
<hr>
Not sure if it's the best message, but I've picked it in https://github.com/mgechev/codelyzer/issues/519#issuecomment-366785640.
> chore: add deprecation message to 'pipe-naming' rule

- src/noInputPrefixRule.ts
- test/noInputPrefixRule.spec.ts
Fixed according to discussion in #594.
> fix(no-input-prefix): exact strings not being reported

- src/noInputRenameRule.ts
- src/noOutputRenameRule.ts
- test/noOutputRenameRule.spec.ts
> fix(rule): some cases not being reported by no-output-rename rule

- src/angularWhitespaceRule.ts
- src/componentClassSuffixRule.ts
- src/componentSelectorRule.ts
- src/contextualLifeCycleRule.ts
- src/decoratorNotAllowedRule.ts
- src/directiveClassSuffixRule.ts
- src/directiveSelectorRule.ts
- src/i18nRule.ts
- src/importDestructuringSpacingRule.ts
- src/maxInlineDeclarationsRule.ts
- src/noInputPrefixRule.ts
- src/noLifeCycleCallRule.ts
- src/noOutputNamedAfterStandardEventRule.ts
- src/noOutputOnPrefixRule.ts
- src/noTemplateCallExpressionRule.ts
- src/pipeNamingRule.ts
- src/preferInlineDecoratorRule.ts
- src/templateConditionalComplexityRule.ts
- src/templateCyclomaticComplexityRule.ts
- src/trackByFunctionRule.ts
- src/useInputPropertyDecoratorRule.ts
- src/useOutputPropertyDecoratorRule.ts
PR https://github.com/palantir/tslint/pull/2527 deprecated passing an `array` of strings for `optionExamples`.
In addition to this, I've refactored the metadata in general to be more generic as `tslint` does, using `const` variables for `options` and so on.
> docs: remove option examples deprecated usage

- src/angular/index.ts
- src/index.ts
> feat: externalize ngWalker to support custom lint rules

- src/noInputRenameRule.ts
- test/noInputRenameRule.spec.ts
> fix(no-input-rename): aria attributes not being allowed to be renamed

- package-lock.json
- package.json
- src/angular/metadataReader.ts
- src/angular/urlResolvers/abstractResolver.ts
- src/index.ts
- src/preferInlineDecoratorRule.ts
- src/selectorNameBase.ts
- src/util/astQuery.ts
- src/util/ngQuery.ts
- src/util/utils.ts
- test/componentSelectorRule.spec.ts
- Downgrade to TypeScript 2.7 which is the officially supported on by `@angular/core`
- Export `preferInlineDecoratorRule`
We should introduce a public API guard to make sure we don't hit
regressions like the second one.
Fix #669 #670
> fix: regressions in 4.4.0

- README.md
Adds the following rules to README:
- no-template-call-expression;
- no-queries-parameter;
- prefer-inline-decorator;
> docs(readme): add missing rules

- src/noOutputOnPrefixRule.ts
- test/noOutputOnPrefixRule.spec.ts
this commit fixes incorrect behavior when memberName contains 'on' suffix in the word, for example selectionChanged.
```
/on((?![a-z])|(?=$))/.test('selectionChanged');
// true
/^on((?![a-z])|(?=$))/.test('selectionChanged');
// false
```
> fix(no-output-on-prefix): fix regular expression

- src/angular/metadataReader.ts
- test/angular/metadataReader.spec.ts
Fixed bug when url is not passed to transformStyle function when using styleUrls.
> fix: url not passed to transformStyle when using styleUrls

- src/templatesNoNegatedAsyncRule.ts
- test/templatesNoNegatedAsyncRule.spec.ts
Relates to #615, it:
- Remove `hasFix` option (code and tests were updated as well);
- Fixes all the cases described in the issue above;
<hr>
About deprecate/drop this rule, I'll do another PR once I'm allowed to do so.
> fix(templates-no-negated-async): not reporting failures for some cases

- src/componentSelectorRule.ts
> docs: component-selector both element and attribute rule

- src/angular/ngWalker.ts
- src/noUnusedCssRule.ts
Fixes #692 #699.
It was a regression caused by PR #587. I'm not sure how we can add tests to prevent errors like this from popping up.
>  fix: errors not being displayed in the correct files

- test/testHelper.ts
Fix #703.
I think try catch statement inside assertFailure() is unnecessary. Because:
1. If exception happens in lint(), this test case should be treated as a fail test. This exception should be catch by Chai.
2. It's unnecessary to print exception stack. Chai will print it in a better place and format.
> fix: assertFailure catch exception throw by assert (#703)

- src/noUnusedCssRule.ts
- test/noUnusedCssRule.spec.ts
Currently, when you use `no-unused-css`'s *autofix*, it only replaces the unused classes with an empty string, which results in many blank lines. Sample:
**Input**:
```css
.test {
color: #fff;
}
div{color: #fff;}
.test-2 {
color: #fff;
}
.test-3 {color: #fff}
.test-4{                color:#fff;font-size: 12px;
}
button {
color: #fff;
}
```
**Current output**:
```diff
- .test {
-   color: #fff;
- }
- div{color: #fff;}
- .test-2 {
-   color: #fff;
- }
- .test-3 {color: #fff}
- .test-4{                color:#fff;font-size: 12px;
- 
- 
- 
+ div{color: #fff;}
- }
button {
color: #fff;
}
```
**Output using these changes**:
```diff
- .test {
-   color: #fff;
- }
- div{color: #fff;}
- .test-2 {
-   color: #fff;
- }
- .test-3 {color: #fff}
- .test-4{                color:#fff;font-size: 12px;
- 
- …
```
> fix(no-unused-css): blank lines being left after fixing

- src/index.ts
- src/relativeUrlPrefixRule.ts
- test/relativeUrlPrefixRule.spec.ts
The ./ prefix is standard syntax for relative URLs; don't depend on Angular's current ability to do without that prefix.
Rationale: A component relative URL requires no change when you move the component files, as long as the files stay together.
related to #623
> feat(rule): add new Rule RelativePathExternalResourcesRule

- README.md
Since angular-whitespace was deprecated and has known issues that won't be fixed, we should not
recommend it in a default configuration.
> doc(readme): don't recommend deprecated angular-whitespace

- src/noTemplateCallExpressionRule.ts
- test/noTemplateCallExpressionRule.spec.ts
Hey Minko and co!
`$any` can be used to bypass issues with template typings when `fullTemplateTypeCheck` is on, but codelyzer doesn't seem to know about it, this PR fixes that
I'm not very familiar with how this project works so I've got a few open questions about my implementation:
1. Should the fix be applied in `visitFunctionCall` as well?
2. Should the fix be applied to the parent `RecursiveAngularExpressionVisitor` class instead?
3. Should a new rule be added (in a follow up PR) to disallow the use of `$any`, similar to the [tslint rule](https://palantir.github.io/tslint/rules/no-any/)?
> fix(allow-template-call-expression): allow $any in expressions

- src/componentChangeDetectionRule.ts
- src/index.ts
- test/componentChangeDetectionRule.spec.ts
Please let me know if there's any changes I need to make! 😄 
Closes #135
> feat(component-change-detection): add change detection strategy rule

- README.md
As the `relative-url-prefix` rule will only be available in version 4.6.0, keeping it on the README **now** (actually in 4.5.0) may cause some confusion.
> docs: remove relative-url-prefix rule

- CHANGELOG.md
- README.md
For some reason it wasn't automatically added by changelog generator. Also, I think it was supposed only to be available in 4.5.0, however, I tested it and it was available since 4.4.3.
> docs: add missing pipe-prefix rule

- src/index.ts
- src/templateNoAnyRule.ts
- test/templateNoAnyRule.spec.ts
Please, check if the description, rationale and failure are clear enough :)
Issue: #633
> feat: add template-no-any rule

- src/angularWhitespaceRule.ts
Once someone tries to use `angular-whitespace` rule will receive the following message: 
> angular-whitespace is deprecated. Use a formatter like Prettier for formatting purposes.
> refactor(rule): add deprecation message for 'angular-whitespace'

- src/componentMaxInlineDeclarationsRule.ts
- src/index.ts
- test/componentMaxInlineDeclarationsRule.spec.ts
Part of #754.
To be in sync with other `component-*` rules.
> refactor(rule): rename 'max-inline-declarations' to 'component-max-inline-declarations'

- src/preferInlineDecoratorRule.ts
- test/preferInlineDecoratorRule.spec.ts
…assed as options
Currently, the rule allows only eight options/decorators to be passed.
> fix(rule): 'prefer-inline-decorator' limiting the number of options

- src/angular/metadata.ts
- src/angular/metadataReader.ts
- src/angular/ngWalker.ts
- src/contextualLifecycleRule.ts
- src/noOutputRenameRule.ts
- src/noPipeImpureRule.ts
- src/pipePrefixRule.ts
- src/util/utils.ts
- test/angular/metadataReader.spec.ts
- test/angular/ngWalker.spec.ts
- test/noPipeImpureRule.spec.ts
> refactor: improve ngWalker by preventing an error when a class has no name

- src/noAttributeDecoratorRule.ts
- src/preferInlineDecoratorRule.ts
- src/util/object-keys.ts
- src/util/utils.ts
- test/preferInlineDecoratorRule.spec.ts
- The rule `prefer-inline-decorator`:
- Doesn't report failures for non **call expression** decorators (Actually, the culpirit is the utility function `getDecoratorName`, which throws an error if you try to get a name of a `decorator` that isn't a **call expression**);
- Doesn't report failures for getters, setters, parameters and parameters properties. To handle this (separately),  options are being added. Users can disable according to their project standards.
- Its fix is **unsafe**. If the `fix` is applied to a property/method with multiple decorators, it just keeps the first decorator (from top) and aligns the property/method with this remaining decorator. I've opted to remove the `hasFix` _option_, because it would be a pain to handle all possible cases correctly.
> refactor(rule): rework prefer-inline-decorator to accept options

- src/templateUseTrackByFunctionRule.ts
- test/templateUseTrackByFunctionRule.spec.ts
Prettier formats some *ngFor expressions across multiple lines which currently isn't picked up by codelyzer, I'm not sure if there is a tighter way of fixing this rather than just deleting the start of the regexp, but all the tests pass so maybe this is enough 😄
> fix(rule): detect trackBy function when ngFor spans  multiple lines

- src/contextualDecoratorRule.ts
- test/contextualDecoratorRule.spec.ts
This:
- Fixes a bug introduced in the new version; (Currently it's not reporting failures if the decorator has arguments due to https://github.com/mgechev/codelyzer/blob/c07ac5e085365562301672cef4e59f159b7a84d0/src/contextualDecoratorRule.ts#L66
- Reports failures for `accessors` with decorators (ex. `@Input`, `@ViewChild`);
- Reports failures for `parameter properties` decorators (ex. `@Attribute`, `@Host`, etc...);
Fixes #776.
>  fix(rule): 'contextual-decorator' - decorators with arguments, accessors and some missing decorators not being handled

- README.md
These rules are defined in the latest Angular template ([here](https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/workspace/files/tslint.json.template)) and were missing from the recommended rules list.
> Add missing recommended rules

- package-lock.json
- package.json
- src/templateConditionalComplexityRule.ts
angular/angular#31391 introduces a breaking change to `parseAction`,
which now requires at least three parameters. This provides a
fix-forward for when the change lands.
> fix(angular): update function call broken by Angular changes

- package.json
Tslint 6.0+ adds support for TypeScript 3.8 syntax. 
https://github.com/palantir/tslint/pull/4915
> fix: add support for tslint 6.0+

- CONTRIBUTING.md
Relative links to external sites only lead you to a 404 🤷‍♂️
Switch to absolute maybe?
> Change relative link to external site to absolute
